### PR TITLE
Add pins numbers for ESP8266 and make sure demo runs forever

### PR DESCRIPTION
**Pull request by marcmerlin**

### CODE REVIEW

**Comment by ladyada** [comment]
heya thanks - there's infinite different pinout setups, we dont want to have anything but the most basic setup here - for ESP folks, they'd need to look at their board and pick the best pin options!

**Comment by marcmerlin** [comment]
Fair enough @ladyada . I thought adding more working default pins saved people time or picking the wrong pins and doing swSPI by mistake instead of hwSPI, but your call.
I realize it's bad practise to send 2 things in one CL, but maybe you'll consider moving the code from setup() to loop() so that it runs forever instead of stopping after one run?

**Comment by ladyada** [comment]
i think lets keep this demo as is, it doesn't have a lot of benefit to run repeatedly and it hasn't been an issue

**Comment by marcmerlin** [comment]
understood, thanks for getting back to me.

**Pull request closed without merging**
