### PR TITLE
Implemented sendCommand, fixed an init commands and fixed test example

### PR DESCRIPTION
**Pull request by makermelissa**

### CODE REVIEW

**Comment by makermelissa** [comment]
Apparently the bmp example needs to be fixed too. I'm working on this.

**Comment by PaintYourDragon** [comment]
Since it’s a subclass of SPITFT, the BMP example can now use the Adafruit_ImageReader library.

This is very Very VERY much preferred as we’d like to squash the 10,000 diverging broken implementations of BMP loading that have spread across various repos.

That example could go in the Adafruit_ImageReader repo (you’ll see the examples for various other displays there) and removed from this one. I just hadn’t gotten to it yet.

**Comment by makermelissa** [comment]
Sounds good. Thank you.

**Comment by makermelissa** [comment]
Ok, tested and working on Teensy 3.6 and ESP8266 as well as Metro now.

**Pull request merged**
